# Getting Started

`NumCompute` is a python library dedicated for educational purpose. It's built upon pure python and numpy. To install this library, please follow `README.md`. For this quickstart, you can uncomment the code block below to prepare environment and install `NumCompute`.  

In [44]:
# NOTE: Uncomment these lines to create and run this notebook in conda environment
# !conda create --name quickstart python=3.11 numpy
# !conda activate quickstart

# NOTE: If you haven't installed NumCompute, uncomment this line to install our module first 
# !pip install -e ..

Since `NumCompute` based on `numpy`, let's import `numpy` to create arrays and also do some setup for better display.

In [45]:
import numpy as np

# Set print options so it will be easier to follow printed arrays
np.set_printoptions(linewidth=200)

## Loading data

`NumCompute` allows loading data with its `io` module. You can load data from any csv file using `load_csv`, carefully adjusting its argument to match your specific data source.

Below is an example where we load **Wine target dataset** from a csv file we provided, which contains 1599 samples with 12 real features. Since this file using semi-colon instead of commonly used colon, we have to specify delimiter as `";"`. The csv files are downloaded from [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/186/wine+target)

In [46]:
from numcompute.io import load_csv

wine = load_csv("../assets/winetarget-red.csv", dtype=np.float32, delimiter=";")
wine.shape

FileNotFoundError: [Errno 2] No such file or directory: '..\\assets\\winetarget-red.csv'

Let's take a quick look at our data. As you can see, our data is loaded as a 2d-array `wine` with `dtype=float32`

In [ ]:
wine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]], dtype=float32)

## Pre-processing and Statistics

After loading data, you can exploring and processing your data using our `stats` and `preprocessing` modules.

In [ ]:
from numcompute.stats import mean, median, std, min, max
from numcompute.preprocessing import MinMaxScaler

Let's inspecting our data. You can compute the statistics (mean, median, std) of any array using `numcompute.stats` module as demonstrated below. Note how we specify the `axis=1` to correctly compute the statistics specific to each features.

In [ ]:
mean(wine, axis=1)

array([ 6.211983, 10.254567,  8.308251, ...,  8.373478,  8.767955,  7.707708], dtype=float32)

In [ ]:
median(wine, axis=1)

array([2.705    , 2.9      , 2.78     , ..., 2.8600001, 2.7849998, 3.495    ], dtype=float32)

In [ ]:
std(wine, axis=1)

array([ 9.127751 , 18.378534 , 14.469733 , ..., 12.29882  , 13.601475 , 11.5264015], dtype=float32)

Let's also check the min and max values for each features.

In [ ]:
min(wine, axis=1), max(wine, axis=1)

(array([0.   , 0.   , 0.04 , ..., 0.076, 0.075, 0.067], dtype=float32),
 array([34., 67., 54., ..., 40., 44., 42.], dtype=float32))

Now, let's try pre-processing our data using `MinMaxScaler`, which scale each features into range [0,1].

In [ ]:
scaler = MinMaxScaler()
wine = scaler.fit_transform(wine)

Let's re-check the min and max of our data after processing 

In [ ]:
min(wine, axis=1), max(wine, axis=1)

(array([0.        , 0.        , 0.04      , ..., 0.09589041, 0.07534247, 0.0918197 ]),
 array([0.60629909, 0.52054793, 0.5088094 , ..., 0.6       , 0.65354313, 0.6       ]))

## Sorting, Searching and Ranking

You can also sort and search any array with our `sort_search`, or rank the elements of an array with `rank`.

In [ ]:
from numcompute.sort_search import multi_key_sort, topk
from numcompute.rank import rank, percentile

Let's try sorting our data with `multi_key_sort`, with which you can sort your your data using any features in any order. Note that here we are indexing `[:10]` to only show the first 10 records after sorted.

In [ ]:
multi_key_sort(wine, columns=[3,2,1])[:10]

array([[0.30088497, 0.0410959 , 0.37      , 0.        , 0.06176961, 0.49295775, 0.3639576 , 0.        , 0.11811029, 0.06586825, 0.66153849, 0.6       ],
       [0.30088497, 0.0410959 , 0.37      , 0.        , 0.06176961, 0.49295775, 0.3639576 , 0.        , 0.11811029, 0.06586825, 0.66153849, 0.6       ],
       [0.23893808, 0.36301367, 0.        , 0.02054795, 0.0884808 , 0.1971831 , 0.05300353, 0.33259958, 0.51181101, 0.08383233, 0.2461539 , 0.8       ],
       [0.07079648, 0.42465753, 0.        , 0.02054795, 0.04841402, 0.21126761, 0.14134276, 0.18428838, 1.        , 0.1556886 , 0.63076929, 0.6       ],
       [0.03539824, 0.42465753, 0.        , 0.02054795, 0.04841402, 0.21126761, 0.14134276, 0.18428838, 1.        , 0.1556886 , 0.63076929, 0.6       ],
       [0.1946903 , 0.47602738, 0.        , 0.02054795, 0.4257095 , 0.21126761, 0.08127208, 0.34067814, 0.45669277, 0.10778442, 0.2153847 , 0.        ],
       [0.36283186, 0.47945204, 0.02      , 0.02054795, 0.09682805, 0.49295775, 0.

To select the top-k values of any features, you can use `topk` function, which select the top-k values and also return the indices of the selected values.

In [ ]:
topk(wine[:, 0], k=5)

(array([1.        , 0.97345139, 0.97345139, 0.9646018 , 0.9646018 ]),
 array([652, 557, 442, 554, 555], dtype=int64))

Or you can find out the numerical ranks to values of a feature.

In [ ]:
rank(wine[:, 0], method="ordinal")

array([531, 722, 723, ..., 121,  58,  71], dtype=int64)

Or you can compute the q-th percentile(s) of a feature

In [ ]:
percentile(wine[:, 0], q=98)

0.716814169001305

## Optimization

With `optim` module, you can easily compute gradients for iterative optimization algorithms.

In [ ]:
from numcompute.optim import grad

Let's try defining some random parameters and compute its gradient with respect to a simple MSE loss.

In [ ]:
from numcompute.metrics import mean_squared_error

# First we split our data into variables and target
variables = wine[:, :11]
target = wine[:, [11]]

# To compute the gradient of MSE loss with respecto parameters, we have to wrap
# every computation inside a single function
def forward(param):
    global variables, target
    batched_target = np.repeat(target, param.shape[0], axis=-1)
    pred = variables @ param.transpose()
    mse_loss = mean_squared_error(batched_target, pred, axis=0)
    return mse_loss

param = np.random.rand(11)
g = grad(forward, param)
print("gradient", g)

gradient [0.41872263 0.34719706 0.34272671 0.16838312 0.16838312 0.28461218 0.20116568 0.63180923 0.56326389 0.25033951 0.36358833]


Let's try updating our parameters using the computed gradients. Note how the updated parameters yield lower MSE loss, which demonstrate how this gradient can be used for optimization.

In [ ]:
print("initial param", param)
print("loss before", forward(param[np.newaxis]))
updated_param = param - 0.1 * g
print("updated param", updated_param)
print("loss after", forward(updated_param[np.newaxis]))

initial param [0.56950809 0.26876967 0.96820738 0.2731649  0.1010985  0.56428617 0.59013836 0.29030503 0.49529883 0.91840692 0.47270635]
loss before [0.97978944]
updated param [0.50602915 0.21810572 0.90979483 0.25289932 0.07636257 0.52286094 0.55973999 0.1949376  0.41334245 0.88175007 0.41369775]
loss after [0.664248]


## Benchmark

Finally, let's run a benchmark to see how vectorization make everything faster.

In [ ]:
from numcompute.benchmarking import main

main()

Start benchmark optim.py
--------------------------------------------------

Benchmark: grad
loop: 0.000158 seconds
vectorized: 0.000060 seconds
vectorized is 2.62x compared to loop
--------------------------------------------------

Benchmark: jacobian
loop: 0.000212 seconds
4
output_index 0


ValueError: The input vectors is not 1 dimension! Input had 2 dimension.