# Getting Started

`NumCompute` is a python library dedicated for educational purpose. It's built upon pure python and numpy. To install this library, please follow `README.md`. For this quickstart, you can uncomment the code block below to prepare environment and install `NumCompute`.  

In [89]:
# NOTE: Uncomment these lines to create and run this notebook in conda environment
# !conda create --name quickstart python=3.11 numpy
# !conda activate quickstart

# NOTE: If you haven't installed NumCompute, uncomment this line to install our module first 
# !pip install -e ..

Since `NumCompute` based on `numpy`, let's import `numpy` to create arrays and also do some setup for better display.

In [90]:
import numpy as np

# Set print options so it will be easier to follow printed arrays
np.set_printoptions(linewidth=200)

## Loading data

`NumCompute` allows loading data with its `io` module. You can load data from any csv file using `load_csv`, carefully adjusting its argument to match your specific data source.

Below is an example where we load **Wine target dataset** from a csv file we provided, which contains 1599 samples with 12 real features. Since this file using semi-colon instead of commonly used colon, we have to specify delimiter as `";"`. The csv files are downloaded from [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/186/wine+target)

In [91]:
from numcompute.io import load_csv

wine = load_csv("../assets/winequality-red.csv", dtype=np.float32, delimiter=";")
wine.shape

(1599, 12)

Let's take a quick look at our data. As you can see, our data is loaded as a 2d-array `wine` with `dtype=float32` and `shape=(1599,12)`, corresponding

In [92]:
wine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]], dtype=float32)

## Pre-processing and Statistics

After loading data, you can exploring and processing your data using our `stats` and `preprocessing` modules.

In [93]:
from numcompute.stats import mean, median, std, min, max
from numcompute.preprocessing import MinMaxScaler, StandardScaler
from numcompute.pipeline import Pipeline

Let's inspecting our data. You can compute the statistics (mean, median, std) of any array using `numcompute.stats` module as demonstrated below. Note how we specify the `axis=0` to correctly compute the statistics specific to each features.

In [94]:
mean(wine, axis=0)

array([ 8.319636  ,  0.5278205 ,  0.27097574,  2.5388057 ,  0.08746663, 15.874922  , 46.467793  ,  0.996747  ,  3.3111079 ,  0.65814954, 10.422993  ,  5.6360226 ], dtype=float32)

In [95]:
median(wine, axis=0)

array([ 7.9    ,  0.52   ,  0.26   ,  2.2    ,  0.079  , 14.     , 38.     ,  0.99675,  3.31   ,  0.62   , 10.2    ,  6.     ], dtype=float32)

In [96]:
std(wine, axis=0)

array([1.7405491e+00, 1.7900370e-01, 1.9474047e-01, 1.4094852e+00, 4.7050551e-02, 1.0456891e+01, 3.2885044e+01, 1.8867436e-03, 1.5433824e-01, 1.6945381e-01, 1.0653349e+00, 8.0731940e-01],
      dtype=float32)

Let's also check the min and max values for each features.

In [97]:
min(wine, axis=0), max(wine, axis=0)

(array([4.6    , 0.12   , 0.     , 0.9    , 0.012  , 1.     , 6.     , 0.99007, 2.74   , 0.33   , 8.4    , 3.     ], dtype=float32),
 array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     , 289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ], dtype=float32))

Now, let's try pre-processing our data using `MinMaxScaler`, which scale each features into range [0,1].

In [98]:
scaler = MinMaxScaler()
# scaler = StandardScaler()
wine = scaler.fit_transform(wine)

Let's re-check the min and max of our data after processing 

In [99]:
min(wine, axis=0), max(wine, axis=0)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

We can also chained processor into a Pipeline, which significantly simplify our code as we don't have to repeatedly call fit_transform.

In [100]:
pipe = Pipeline([
    ("scaler1", StandardScaler()),
    ("scaler2", MinMaxScaler())
])

wine = pipe.fit_transform(wine)

In [101]:
min(wine, axis=0), max(wine, axis=0)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]))

## Sorting, Searching and Ranking

You can also sort and search any array with our `sort_search`, or rank the elements of an array with `rank`.

In [102]:
from numcompute.sort_search import multi_key_sort, topk
from numcompute.rank import rank, percentile

Let's try sorting our data with `multi_key_sort`, with which you can sort your your data using any features in any order. Note that here we are indexing `[:10]` to only show the first 10 records after sorted.

In [103]:
multi_key_sort(wine, columns=[2,1])[:10]

array([[0.05309734, 0.15068493, 0.        , 0.06164383, 0.06343907, 0.36619718, 0.20141343, 0.11233403, 0.7401574 , 0.27544911, 0.86153852, 0.6       ],
       [0.05309734, 0.15068493, 0.        , 0.06164383, 0.06343907, 0.36619718, 0.20141343, 0.11233403, 0.7401574 , 0.27544911, 0.86153852, 0.6       ],
       [0.02654869, 0.20547944, 0.        , 0.08219178, 0.06010017, 0.21126761, 0.12720848, 0.10793152, 0.76377942, 0.24550898, 0.86153852, 0.8       ],
       [0.04424779, 0.20547944, 0.        , 0.06164383, 0.05342237, 0.23943662, 0.28975265, 0.11013278, 0.7401574 , 0.23952096, 0.80000012, 0.8       ],
       [0.20353985, 0.21917808, 0.        , 0.03424658, 0.09682805, 0.43661972, 0.1130742 , 0.31644683, 0.45669277, 0.14970058, 0.46153846, 0.6       ],
       [0.11504427, 0.21917808, 0.        , 0.04794521, 0.05008347, 0.02816901, 0.01766784, 0.31791725, 0.58267707, 0.31137725, 0.50769234, 0.6       ],
       [0.11504427, 0.23287671, 0.        , 0.06849315, 0.10851419, 0.33802817, 0.

To select the top-k values of any features, you can use `topk` function, which select the top-k values and also return the indices of the selected values.

In [104]:
topk(wine[:, 0], k=5)

(array([1.        , 0.97345139, 0.97345139, 0.9646018 , 0.9646018 ]),
 array([652, 557, 442, 554, 555], dtype=int64))

Or you can find out the numerical ranks to values of a feature.

In [105]:
rank(wine[:, 0], method="ordinal")

array([531, 722, 723, ..., 121,  58,  71], dtype=int64)

Or you can compute the q-th percentile(s) of a feature

In [106]:
percentile(wine[:, 0], q=98)

0.7168141690013051

## Optimization

With `optim` module, you can easily compute gradients for iterative optimization algorithms.

In [107]:
from numcompute.optim import grad

Let's try defining some random parameters and compute its gradient with respect to a simple MSE loss.

In [108]:
from numcompute.metrics import mean_squared_error

# First we split our data into variables and target
variables = wine[:, :11]
target = wine[:, [11]]

# To compute the gradient of MSE loss with respecto parameters, we have to wrap
# every computation inside a single function
def forward(param):
    global variables, target
    batched_target = np.repeat(target, param.shape[0], axis=-1)
    pred = variables @ param.transpose()
    mse_loss = mean_squared_error(batched_target, pred, axis=0)
    return mse_loss

param = np.zeros(11)
g = grad(forward, param)
print("gradient", g)

gradient [-0.56773424 -0.49173832 -0.46044588 -0.40084124 -0.43362379 -0.43511391 -0.33974648 -0.70780516 -0.59753656 -0.46789646 -0.52303076]


Let's try updating our parameters using the computed gradients. Note how the updated parameters yield lower MSE loss, which demonstrate how this gradient can be used for optimization.

In [109]:
print("initial param", param)
print("loss before", forward(param[np.newaxis]))
updated_param = param - 0.1 * g
print("updated param", updated_param)
print("loss after", forward(updated_param[np.newaxis]))

initial param [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
loss before [0.30401504]
updated param [0.05677342 0.04917383 0.04604459 0.04008412 0.04336238 0.04351139 0.03397465 0.07078052 0.05975366 0.04678965 0.05230308]
loss after [0.16373621]


## Benchmark

Finally, let's run a benchmark to see how vectorization make everything faster. As can be seen in the displayed table, our module with vectorization can speed up operations by up to 300x, comparing to python loop. 

In [110]:
from numcompute.benchmarking import main
from IPython.display import Markdown, display

results = main()

rows = []
for module, benchmarks in results.items():
    for benchmark_name, timings in benchmarks.items():
        rows.append(
            {
                "Module": module,
                "Benchmark": benchmark_name,
                "Loop (s)": timings["loop"],
                "Vectorized (s)": timings["vectorized"],
                "Speedup (x)": timings["speedup"],
            }
        )

rows.sort(key=lambda row: row["Speedup (x)"], reverse=True)

header = "| Module | Benchmark | Loop (s) | Vectorized (s) | Speedup (x) |"
separator = "|---|---|---:|---:|---:|"
body = [
    f"| {row['Module']} | {row['Benchmark']} | {row['Loop (s)']:.6f} | {row['Vectorized (s)']:.6f} | {row['Speedup (x)']:.2f} |"
    for row in rows
]

table_md = "\n".join([header, separator, *body])
display(Markdown(table_md))

Start benchmark optim.py
--------------------------------------------------

Benchmark: grad
loop: 0.000062 seconds
vectorized: 0.000022 seconds
vectorized is 2.81x compared to loop
--------------------------------------------------

Benchmark: jacobian
loop: 0.000133 seconds
vectorized: 0.000058 seconds
vectorized is 2.27x compared to loop
Start benchmark preprocessing.py
--------------------------------------------------

Benchmark: standard_scaler
loop: 0.006966 seconds
vectorized: 0.000122 seconds
vectorized is 57.33x compared to loop
--------------------------------------------------

Benchmark: minmax_scaler
loop: 0.004780 seconds
vectorized: 0.000082 seconds
vectorized is 58.13x compared to loop
--------------------------------------------------

Benchmark: one_hot_encoder
loop: 0.003550 seconds
vectorized: 0.000350 seconds
vectorized is 10.13x compared to loop
--------------------------------------------------

Benchmark: simple_imputer
loop: 0.006256 seconds
vectorized: 0.0001

| Module | Benchmark | Loop (s) | Vectorized (s) | Speedup (x) |
|---|---|---:|---:|---:|
| sort_search | stable_sort | 0.017695 | 0.000029 | 603.87 |
| sort_search | multi_key_sort | 0.036067 | 0.000121 | 297.82 |
| stats | std | 0.002406 | 0.000030 | 79.10 |
| metrics | accuracy_score | 0.001451 | 0.000019 | 77.75 |
| metrics | mean_squared_error | 0.002250 | 0.000030 | 73.93 |
| preprocessing | minmax_scaler | 0.004780 | 0.000082 | 58.13 |
| preprocessing | standard_scaler | 0.006966 | 0.000122 | 57.33 |
| metrics | f1_score | 0.005300 | 0.000095 | 56.03 |
| metrics | recall_score | 0.002660 | 0.000050 | 52.74 |
| metrics | precision_score | 0.002668 | 0.000052 | 51.41 |
| stats | median | 0.002242 | 0.000045 | 49.62 |
| stats | mean | 0.000553 | 0.000012 | 47.88 |
| stats | max | 0.000362 | 0.000008 | 44.07 |
| stats | min | 0.000324 | 0.000008 | 42.24 |
| preprocessing | simple_imputer | 0.006256 | 0.000182 | 34.33 |
| sort_search | quickselect | 0.000219 | 0.000008 | 26.41 |
| sort_search | topk | 0.000130 | 0.000009 | 14.15 |
| preprocessing | one_hot_encoder | 0.003550 | 0.000350 | 10.13 |
| rank | rank | 0.000527 | 0.000056 | 9.44 |
| metrics | confusion_matrix | 0.002518 | 0.000340 | 7.40 |
| optim | grad | 0.000062 | 0.000022 | 2.81 |
| optim | jacobian | 0.000133 | 0.000058 | 2.27 |
| sort_search | binary_search | 0.000010 | 0.000005 | 2.12 |
| rank | percentile | 0.000053 | 0.000065 | 0.81 |