# Getting Started

`NumCompute` is a python library dedicated for educational purpose. It's built upon pure python and numpy. To install this library, please follow `README.md`. For this quickstart, you can uncomment the code block below to prepare environment and install `NumCompute`.  

In [29]:
# NOTE: Uncomment these lines to create and run this notebook in conda environment
# !conda create --name quickstart python=3.10 numpy
# !conda activate quickstart

# NOTE: If you haven't installed NumCompute, uncomment this line to install our module first 
# !pip install -e ..

Since `NumCompute` based on `numpy`, let's import `numpy` to create arrays and also do some setup for better display.

In [30]:
import numpy as np

# Set print options so it will be easier to follow printed arrays
np.set_printoptions(linewidth=200)

## Loading data

`NumCompute` allows loading data with its `io` module. You can load data from any csv file using `load_csv`, carefully adjusting its argument to match your specific data source.

Below is an example where we load **Wine Quality dataset** from a csv file we provided, which contains 1599 samples with 12 real features. Since this file using semi-colon instead of commonly used colon, we have to specify delimiter as `";"`. The csv files are downloaded from [UCI Machine Learning Repository](https://archive.ics.uci.edu/dataset/186/wine+quality)

In [31]:
from numcompute.io import load_csv

wine = load_csv("../assets/winequality-red.csv", dtype=np.float32, delimiter=";")
wine.shape

(1599, 12)

In [32]:
wine

array([[ 7.4  ,  0.7  ,  0.   , ...,  0.56 ,  9.4  ,  5.   ],
       [ 7.8  ,  0.88 ,  0.   , ...,  0.68 ,  9.8  ,  5.   ],
       [ 7.8  ,  0.76 ,  0.04 , ...,  0.65 ,  9.8  ,  5.   ],
       ...,
       [ 6.3  ,  0.51 ,  0.13 , ...,  0.75 , 11.   ,  6.   ],
       [ 5.9  ,  0.645,  0.12 , ...,  0.71 , 10.2  ,  5.   ],
       [ 6.   ,  0.31 ,  0.47 , ...,  0.66 , 11.   ,  6.   ]], dtype=float32)

Let's inspecting our data. You can compute the statistics any array using `numcompute.stats` module as demonstrated below. On top of the functionalities provided by numpy, `numcompute.stats` provide an quick and easy interface to deal with NaN values.

## Pre-processing and Statistics

After loading data, you can exploring and processing your data using our `stats` and `preprocessing` modules.

In [33]:
from numcompute.stats import mean, median, std, min, max
from numcompute.preprocessing import MinMaxScaler

In [34]:
min(wine, axis=1), max(wine, axis=1)

(array([0.   , 0.   , 0.04 , ..., 0.076, 0.075, 0.067], dtype=float32),
 array([34., 67., 54., ..., 40., 44., 42.], dtype=float32))

In [35]:
scaler = MinMaxScaler()
wine = scaler.fit_transform(wine)

In [36]:
min(wine, axis=1), max(wine, axis=1)

(array([0.        , 0.        , 0.04      , ..., 0.09589041, 0.07534247, 0.0918197 ]),
 array([0.60629909, 0.52054793, 0.5088094 , ..., 0.6       , 0.65354313, 0.6       ]))

## Sorting, Searching and Ranking

In [37]:
from numcompute.sort_search import multi_key_sort, topk
from numcompute.rank import rank, percentile

In [44]:
multi_key_sort(wine, columns=[11,1])[:10]

array([[0.51327432, 0.21917808, 0.41999999, 0.04109589, 0.22203672, 0.46478873, 0.14840989, 0.60572589, 0.503937  , 0.31736527, 0.23076923, 0.        ],
       [0.61946908, 0.31506847, 0.66000003, 0.0890411 , 0.10350584, 0.12676056, 0.14487633, 0.78781301, 0.40157473, 0.14371256, 0.09230775, 0.        ],
       [0.51327432, 0.33561644, 0.49000001, 0.08219178, 0.31385643, 0.05633803, 0.03533569, 0.68502359, 0.33070866, 0.17964071, 0.        , 0.        ],
       [0.1858407 , 0.43835615, 0.02      , 0.06164383, 0.11018364, 0.07042254, 0.02120141, 0.43538901, 0.63779512, 0.17964071, 0.23846157, 0.        ],
       [0.1946903 , 0.47602738, 0.        , 0.02054795, 0.4257095 , 0.21126761, 0.08127208, 0.34067814, 0.45669277, 0.10778442, 0.2153847 , 0.        ],
       [0.22123894, 0.51712327, 0.05      , 0.32876711, 0.11686144, 0.02816901, 0.02826855, 0.5881071 , 0.51968502, 0.11377244, 0.27692311, 0.        ],
       [0.23893808, 0.58904109, 0.05      , 0.08219178, 0.08180301, 0.26760563, 0.

In [41]:
topk(wine[:, 0], k=5)

(array([1.        , 0.97345139, 0.97345139, 0.9646018 , 0.9646018 ]),
 array([652, 557, 442, 554, 555], dtype=int64))

In [47]:
rank(wine[:, 0], method="ordinal")

array([531, 722, 723, ..., 121,  58,  71], dtype=int64)

In [48]:
percentile(wine[:, 0], q=98)

0.716814169001305

## Optimization

In [ ]:
from numcompute.optim import 

## Benchmark